README.md
ast.c
ast.h
examples/output_error.brainrot
lang.l
lang.y

Create function `baka(string)` to output to stderr. Its usage is pretty straightforward:
```
skibidi main {
edging (1) {
baka("you sussy baka!");
}
bussin 0;
}
```
You can check it is actually printing to the stderr using the following command:
```sh
[leonardo@archlinux brainrot]$ ./brainrot < examples/output_error.brainrot 2> stderr.txt
[leonardo@archlinux brainrot]$ cat stderr.txt 
you sussy baka!
```

Create function baka to output to stderr

---

README.md
examples/switch_case.brainrot
lang.l

This PR changes the `sigma` keyword to `sigma rule` as requested by @unia909 and endorsed by some fellow chads in issue https://github.com/araujo88/brainrot/issues/3.

refactor: change sigma keyword to sigma rule

---

ast.c
ast.h
examples/fizz_buzz.brainrot
examples/while_loop.brainrot
lang.y

Added support for `nut`, `nonut` and `schizo` modifiers. Fix for https://github.com/Brainrotlang/brainrot/issues/23.

feat: support nut, nonut and schizo modifiers

---

ast.c
ast.h
examples/modulo.brainrot
lang.y

Fixes https://github.com/Brainrotlang/brainrot/issues/25.

Fix: modulo operation (`%`) for `nonut rizz` variables 

---

README.md
ast.c
ast.h
examples/boolean.brainrot
lang.l
lang.y

This PR implements the `cap` keyword (boolean) which could be either `yes` (true) or `no` (false).
Example:
```
skibidi main {
cap is_valid = yes;
cap is_ready = no;
edging(is_valid) {
yapping("It's valid!");
}
is_valid = yes && no;
yapping("%d", is_valid);
is_valid = yes || no;
yapping("%d", is_valid);
}
```

feat: implement `cap` (bool) type

---

README.md
ast.c
ast.h
docs/brainrot-user-guide.md
docs/the-brainrot-programming-language.md
examples/rage_quit.brainrot
lang.y

Added builtin function `ragequit`, which is basically a wrapper for C's `exit` function:
```c
void ragequit(int exit_code) {
exit(exit_code);
}
```
Example of usage:
```
skibidi main {
rizz i = 2;
edgy (i == 2) {
ragequit(69);
} amogus {
ragequit(42);
}
bussin 0;
}
```
To check if it actually returns 69, we can type `echo $?`:
```
[leonardo@archlinux brainrot]$ ./brainrot < examples/rage_quit.brainrot 
[leonardo@archlinux brainrot]$ echo $?
69
```

feat: add builtin function ragequit

---

ast.c
ast.h
examples/bool_array.brainrot
examples/char_array.brainrot
examples/double_array.brainrot
examples/float_array.brainrot
examples/int_array.brainrot
examples/short_array.brainrot
lang.l
lang.y
tests/expected_results.json

Add support for `rizz`, `smol`, `cap`, `yap`, `chad` and `gigachad` arrays.

feat: add support for arrays

---

.github/workflows/ci.yml
Makefile
ast.c
examples/fizz_buzz_short.brainrot
tests/expected_results.json

Adding binary expression for `smol` type also introducing `mod` operator for `chad` and `gigachad` types 
This fix #68

Fix(smol): adding binary expression for short type

---

.github/workflows/ci.yml
Makefile
ast.c
ast.h
lang.y
lib/hm.c
lib/hm.h
lib/mem.c
lib/mem.h

- replace all calls to `malloc`, `free` etc by safe implementations
- add memory leak check to CI

use safe memory lib and add memory leaks checks to CI

---

README.md

Excludes the <b>3rd step</b> of <b>Building the Compiler</b> on README.md :
3rd step can fully be replaced with alternative option `make`.
Fixes issue #19

Fixing the Issue 19 on README.md

---

.github/workflows/ci.yml
Makefile
README.md
ast.c
ast.h
docs/brainrot-user-guide.md
docs/the-brainrot-programming-language.md
lang.l
lang.y
lib/input.c
lib/input.h
run_valgrind_tests.sh
tests/test_brainrot.py

Allows for type-safe user input:
```c
skibidi main {
rizz num;
yapping("Enter a number:");
slorp(num);
yapping("You typed: %d", num);
bussin 0;
}
```
Implements #98.

feat: user input

---

ast.c
lang.y
lib/mem.c

adding memory check in `jumbuf` and arrays

memory checks

---

ast.c

Fix memory leak when slorping a string.

fix: memory leak on slorping a string

---

ast.c
ast.h
lang.y
lib/hm.c
lib/hm.h
lib/mem.h

Fix compiler warnings.
Fixes issue #84

fix: compiler annoying warnings

---

Makefile
ast.c
ast.h
test_cases/fib.brainrot
test_cases/func_scope.brainrot
tests/expected_results.json

This pull request introduces several enhancements and fixes to the codebase, primarily focusing on function handling, scope management, and debugging capabilities. The most important changes include adding a debug build target, improving function call handling, and updating test cases to reflect new functionality.
* Added `DEBUG_FLAGS := -g` to `Makefile` and introduced a new `debug` target for compiling debug builds with GDB support. [[1]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R13) [[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R27-R33)
* Added support for function calls in `get_expression_type` by looking up the function's return type in the symbol table.
* Implemented `enter_function_scope` to handle …

Fix function scope

---

ast.c
run_valgrind_tests.sh

This pull request includes several important changes to memory management and testing procedures in the codebase. The changes focus on improving the handling of function parameters and enhancing the reliability of the test suite.
Memory management improvements:
* [`ast.c`](diffhunk://#diff-85e7043923ed16998bac0e0e85a8a1c8879c81e9f17fa2229692936215805191R3438): Added a call to `free_parameters` to ensure all function parameters are properly freed in `free_ast`.
* [`ast.c`](diffhunk://#diff-85e7043923ed16998bac0e0e85a8a1c8879c81e9f17fa2229692936215805191R3790): Added a call to `SAFE_FREE` for variables in `enter_function_scope` to prevent memory leaks.
* [`ast.c`](diffhunk://#diff-85e7043923ed16998bac0e0e85a8a1c8879c81e9f17fa2229692936215805191R3815): Added a call to …

ci(memory_leaks): Fix CI valgrind check and resolve function memory leaks

---

Makefile
ast.c
ast.h
lang.l
lang.y
lib/arena.c
lib/arena.h
run_valgrind_tests.sh

As the AST grows more complex, managing it becomes increasingly difficult, and free_ast becomes larger. This PR introduces a single Region to allocate all AST nodes, allowing them to be freed at once, simplifying memory management and reducing overhead.

Region-based allocation for AST nodes 

---

ast.c
ast.h
lang.y
run_valgrind_tests.sh
test_cases/func-modifier.brainrot
tests/expected_results.json

This pull request introduces changes to support type modifiers for function parameters in the `ast.c` and `ast.h` files. The changes include updating the `Parameter` structure and modifying relevant functions to handle the new `TypeModifiers` field.
* [`ast.c`](diffhunk://#diff-85e7043923ed16998bac0e0e85a8a1c8879c81e9f17fa2229692936215805191L3479-R3479): Updated the `create_parameter` function to include a `TypeModifiers mods` parameter and modified the `enter_function_scope` function to use the `modifiers` field from the `Parameter` structure instead of the `get_current_modifiers` function. [[1]](diffhunk://#diff-85e7043923ed16998bac0e0e85a8a1c8879c81e9f17fa2229692936215805191L3479-R3479) [[2]](diffhunk://#diff-85e7043923ed16998bac0e0e85a8a1c8879c81e9f17fa2229692936215805191R3491) …

Feat(func): enable type modifer in user defined function

---

ast.c

I try to run the program with `-fsanitize=address,undefined` and this error appear in `output_error` test case
```
❯ ./brainrot test_cases/output_error.brainrot
you sussy baka!
ast.c:3476:9: runtime error: member access within null pointer of type 'struct JumpBuffer'
```
This PR fix this problem
Fixes #<issue_number>

Fix(runtime): access null pointer

---

Makefile
ast.c
ast.h
examples/twoSum.brainrot
lang.y
run_valgrind_tests.sh
test_cases/array_initialization.brainrot
test_cases/multi_array.brainrot
tests/expected_results.json

This PR introduce the implementation of multi dimensional arrays
In the current state we cannot use this syntax
```c
rizz arr[3][3] = {
{1, 2, 3}, 
{4, 5, 6}, 
{7, 8, 9}
};
```
```c
rizz arr[][3] = {
{1, 2, 3}, 
{4, 5, 6}, 
{7, 8, 9}
};
```
or 
```c
rizz arr[] = {
1,
2
};
```
Fixes #96

Introducing multi-dimensional arrays

---

README.md
ast.c
ast.h
lang.l
lang.y
test_cases/grid_bfs.brainrot
test_cases/rant.brainrot
tests/expected_results.json

This pull request introduces comprehensive support for string variables in the `ast.c` file. It adds the ability to assign, evaluate, and use string variables in expressions, function calls, and I/O operations, while refactoring type checking and assignment logic to be more generic and extensible. The changes also streamline the handling of type promotion and assignment for all supported variable types.
**String variable support and type system improvements:**
* Added support for string variables throughout the interpreter, including assignment (`set_string_variable`), expression evaluation (`evaluate_expression_string`), and function call return values. [[1]](diffhunk://#diff-85e7043923ed16998bac0e0e85a8a1c8879c81e9f17fa2229692936215805191R70-R72) …

implement string type (rant)
