Brainrotlang/brainrot

.github/workflows/build.yml

This CI does the following steps:
- Install dependencies
- Build
- Run the examples

Add CI with GitHub Actions

---

.github/workflows/build.yml
ast.c
ast.h
examples/fizz_buzz.brainrot
examples/hello_world.brainrot
examples/while_loop.brainrot
lang.l
lang.y

Handles while loops (`goon` keyword) as pointed out in https://github.com/araujo88/brainrot/issues/7 and adds bulting `yappin` function as suggested as feature in https://github.com/araujo88/brainrot/issues/12.

feat: handles while loops (`goon` keyword) and adds bulting `yappin` function

---

ast.c
ast.h
lang.y

Enhanced error messages for undeclared identifiers.

feat: enhanced error messages for undeclared identifiers

---

README.md
ast.c
docs/the-brainrot-programming-language.md
examples/boolean.brainrot
examples/sizeof.brainrot
lang.l
tests/expected_results.json

- changes `yes` to `W`
- changes `no` to `L`
https://github.com/Brainrotlang/brainrot/issues/44.
Fixes #<issue_number>

refactor: change boolean values keywords

---

README.md

Fixes Discord link in README.
Fixes issue #46.

docs: update discord link in README

---

ast.c
ast.h
examples/boolean.brainrot
lang.y
tests/expected_results.json

Refactor adding a enum value for how a node is identified as a certain type of variable.

refactor: added var_type enum

---

README.md
ast.c
ast.h
docs/the-brainrot-programming-language.md
examples/sizeof.brainrot
lang.l
lang.y
tests/expected_results.json

Implements `smol` keyword (short variable).

feat: smol keyword - short integer variable

---

.github/workflows/ci.yml
README.md
ast.c
ast.h
docs/the-brainrot-programming-language.md
examples/const.brainrot
lang.l
lang.y
tests/expected_results.json
tests/test_brainrot.py

Add support for `deadass` keyword (`const` keyword from C).

feat: deadass keyword for const modifier

---

README.md
ast.c
ast.h
docs/brainrot-user-guide.md
docs/the-brainrot-programming-language.md
examples/do-while.brainrot
lang.y
tests/expected_results.json

adding support for do-while loop

feat: mewing-goon statement

---

ast.c
ast.h
examples/const.brainrot
examples/nest-loop.brainrot
examples/next-prime.brainrot
tests/expected_results.json

Introducing new way to handle long jumps
#61

Fix: nested loop break statement

---

.github/workflows/ci.yml

Remove run example since it is redundant with the `test` step.

ci: remove run examples step

---

docs/brainrot-user-guide.md

fix(doc): flex loop doc

---

ast.c
ast.h
lang.y

Introducing new types in the parser makes to the code more readable and maintainable.

refactor(parser): refactor expresstion and grammer

---

README.md

Remove known issues from README since they were handled.

docs: remove known issues from README

---

ast.c
lang.y

fix(array): memory leaks in ExpressionList

---

Makefile

Add more rizz to the makefile.

refactor: add more rizz to makefile

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
docs/the-brainrot-programming-language.md
run_valgrind_tests.sh

- updated pull request template with refactor option, checks for running the unit tests locally and memory tests locally
- added keyword `lit` for `typedef`
- added shell script for running valgrind tests
- updated contributing guide

Several stuff

---

Makefile

Add `valgrind` to `make help`.

makefile: add valgrind to help

---

README.md

Update README with subreddit link.

docs: update readme with subreddit link

---

ast.c
ast.h
lang.l
lang.y
test_cases/add_two_numbers.brainrot
test_cases/is_prime.brainrot
test_cases/max_gigachad.brainrot
test_cases/mul_two_numbers.brainrot
tests/expected_results.json

Add user-defined functions. Example:
```c
rizz numba_go_up(rizz a, rizz b) {
bussin a + b;
}
skibidi main {
yappin("%d\n", numba_go_up(1, 2));
bussin 0;
}
```

feat: user-defined functions

---

README.md

docs: update limitations

---

docs/the-brainrot-programming-language.md
examples/README.md

User define function Doc

---

README.md

Fix hello world example in README.
Fixes #103.

docs: fix hello world example in README

---

Makefile
README.md

Add install and uninstall rules to makefile.

add install and uninstall rules to makefile

---

Makefile

This PR will enable psycho mode for the compiler so that we are less prone to write shitty code.

Add `Werror` to compiler flags

---

examples/twoSum.brainrot

deleted a g that didn't belong in an example
Things i didnt do aren't needed. its one character lol

Removed a g from "yappign"
